"""convert tenant money fields to numeric

Revision ID: 41f01c67162a
Revises: d0037b857ee4
Create Date: 2026-09-26 18:27:58.223948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f01c67162a'
down_revision: Union[str, Sequence[str], None] = 'd0037b857ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
    "tenants",
    "monthly_budget",
    existing_type=sa.DOUBLE_PRECISION(precision=53),
    type_=sa.Numeric(precision=12, scale=6),
    existing_nullable=False,
    postgresql_using="monthly_budget::numeric(12,6)",
)

    op.alter_column(
    "tenants",
    "current_spend",
    existing_type=sa.DOUBLE_PRECISION(precision=53),
    type_=sa.Numeric(precision=12, scale=6),
    existing_nullable=False,
    postgresql_using="current_spend::numeric(12,6)",
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'current_spend',
               existing_type=sa.Numeric(precision=12, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('tenants', 'monthly_budget',
               existing_type=sa.Numeric(precision=12, scale=6),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
