"""add thinking tokens to usage records

Revision ID: f9540b35ac35
Revises: 41f01c67162a
Create Date: 2026-09-28 09:58:15.088748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9540b35ac35'
down_revision: Union[str, Sequence[str], None] = '41f01c67162a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "usage_records",
        sa.Column(
            "thinking_tokens",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )
    op.alter_column(
        "usage_records",
        "thinking_tokens",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_records', 'thinking_tokens')
    # ### end Alembic commands ###
